type %~dp0\Algorithms.ts > out.ts
type %~dp0\QuestionCategory.ts >> out.ts
type %~dp0\Question.ts >> out.ts
type %~dp0\QuestionDatabase.ts >> out.ts
type %~dp0\QuizHtmlContainer.ts >> out.ts
type %~dp0\QuizStartMenuContainer.ts >> out.ts
type %~dp0\QuizGlobalController.ts >> out.ts
type %~dp0\QuestionBuilder.ts >> out.ts
type %~dp0\QuizAppInstance.ts >> out.ts
